#!/usr/bin/env bats
#
# Tests for the gitlabSetup entrypoint (src/setup.ts) in the gitlab-app image:
# fixtures/setup-mock.mjs runs it inside the image against an in-process
# GitLab + Kubernetes API mock and prints the writes it received. See the
# mock for the instance layout (groups, projects, the bot).

load test_helper

setup_file() {
  require_image
}

# setup_run [-e VAR=value ...] -> mock output (writes + OK/FAILED)
setup_run() {
  docker run --rm -v "$BATS_TEST_DIRNAME/fixtures:/test:ro" "$@" "$IMAGE" node /test/setup-mock.mjs
}

assert_output_lacks() {
  if [[ "$output" == *"$1"* ]]; then
    printf 'expected output not to contain: %s\nactual: %s\n' "$1" "$output" >&2
    return 1
  fi
}

@test "default ['*']: only top-level groups get a membership" {
  run setup_run
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_contains "POST /api/v4/groups/1/members"
  assert_output_contains "POST /api/v4/groups/3/members"
  # team-a/sub inherits from team-a; gone is marked for deletion.
  assert_output_lacks "/api/v4/groups/2/"
  assert_output_lacks "/api/v4/groups/4/"
}

@test "default ['*']: every active project gets the comment webhook" {
  run setup_run
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  # Existing hook (found by name) is updated, the others are created.
  assert_output_contains 'PUT /api/v4/projects/10/hooks/99 {"name":"ai-agent-for-gitlab"'
  assert_output_contains "POST /api/v4/projects/11/hooks"
  assert_output_contains "POST /api/v4/projects/12/hooks"
  assert_output_contains '"note_events":true,"merge_requests_events":false,"push_events":false'
  assert_output_contains '"token":"hook-secret"'
  # Archived project is skipped.
  assert_output_lacks "/api/v4/projects/13/"
}

@test "project membership is skipped when inherited, added otherwise" {
  run setup_run
  [ "$status" -eq 0 ]
  assert_output_lacks "POST /api/v4/projects/10/members"
  assert_output_contains 'POST /api/v4/projects/11/members {"user_id":7,"access_level":30}'
}

@test "system hook is still registered for merge request events" {
  run setup_run
  [ "$status" -eq 0 ]
  assert_output_contains 'POST /api/v4/hooks {"name":"ai-agent-for-gitlab"'
}

@test "globs select matching projects, first entry's settings win" {
  run setup_run -e SETUP_GROUPS='[]' \
    -e SETUP_PROJECTS='[{"path":"TEAM-A/SUB/*","accessLevel":40},"team-a/*"]'
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_lacks "/api/v4/groups/"
  assert_output_contains 'POST /api/v4/projects/11/members {"user_id":7,"access_level":40}'
  assert_output_contains "PUT /api/v4/projects/10/hooks/99"
  assert_output_lacks "/api/v4/projects/12/"
}

@test "merge request events on project hooks only without the system hook" {
  run setup_run -e SYSTEM_HOOK_ENABLED=false -e SETUP_GROUPS='[]' -e SETUP_PROJECTS='["team-b/tool"]'
  [ "$status" -eq 0 ]
  assert_output_contains '"merge_requests_events":true'
  assert_output_lacks "/api/v4/hooks "

  run setup_run -e SETUP_GROUPS='[]' \
    -e SETUP_PROJECTS='[{"path":"team-b/tool","mergeRequestsEvents":true}]'
  [ "$status" -eq 0 ]
  assert_output_contains 'POST /api/v4/projects/12/hooks'
  assert_output_contains '"merge_requests_events":true'
}

@test "plain paths are looked up directly, unknown ones are skipped" {
  run setup_run -e SETUP_GROUPS='team-b,missing' -e SETUP_PROJECTS='["team-b/tool","nope/nope"]'
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_contains "POST /api/v4/groups/3/members"
  assert_output_lacks "/api/v4/groups/1/"
  assert_output_contains "POST /api/v4/projects/12/hooks"
  assert_output_lacks "/api/v4/projects/11/"
}

@test "empty lists turn the group and project steps off" {
  run setup_run -e SETUP_GROUPS='[]' -e SETUP_PROJECTS='[]'
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_lacks "/members"
  assert_output_lacks "/api/v4/projects/"
}

@test "invalid SETUP_PROJECTS fails the setup" {
  run setup_run -e SETUP_PROJECTS='[{"accessLevel":40}]'
  assert_output_contains "FAILED: SETUP_PROJECTS[0] needs a path"
}

@test "deployment is left alone while values and webhook secret are unchanged" {
  run setup_run -e RESTART_DEPLOYMENT=web -e CONFIG_CHECKSUM=chart-sum
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_lacks "/deployments/web"
}

@test "deployment restarts when the webhook secret changed (e.g. regenerated by Argo CD)" {
  run setup_run -e RESTART_DEPLOYMENT=web -e CONFIG_CHECKSUM=chart-sum -e WEBHOOK_SECRET=regenerated
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_contains '"token":"regenerated"'
  assert_output_contains "PATCH /apis/apps/v1/namespaces/test/deployments/web"
}

# setup_run with the central pipeline on (see the mock for its projects)
central_run() {
  setup_run -e CENTRAL_PIPELINE_ENABLED=true \
    -e COMPONENT_PROJECT=ai/ai-agent-for-gitlab \
    -e COMPONENT_CLONE_URL=https://user:secret@github.com/m13tLabs/ai-agent-for-gitlab.git \
    -e RUNNER_PROJECT=ai/agent-runner \
    -e SETUP_GROUPS='[]' -e SETUP_PROJECTS='[]' "$@"
}

@test "central pipeline: component made a catalog resource, runner project created with the bot as Owner" {
  run central_run -e RUNNER_COMPONENT_INPUTS='{"tags":["ai-agent"]}'
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  # Existing component project: description (link without credentials) synced, bot Owner, catalog on.
  assert_output_contains 'PUT /api/v4/projects/30 {"description":"CI/CD component \"agent-runner\" of the AI agent for GitLab, imported from https://github.com/m13tLabs/ai-agent-for-gitlab.'
  assert_output_contains 'POST /api/v4/projects/30/members {"user_id":7,"access_level":50}'
  assert_output_contains 'catalogResourcesCreate(input: { projectPath: $p })'
  assert_output_lacks "secret@"
  # Runner project created in group ai (20), bot Owner, files on a new main branch.
  assert_output_contains 'POST /api/v4/projects {"name":"agent-runner","path":"agent-runner","namespace_id":20'
  assert_output_contains 'POST /api/v4/projects/32/members {"user_id":7,"access_level":50}'
  assert_output_contains 'POST /api/v4/projects/32/repository/commits {"branch":"main"'
  assert_output_contains 'component: $CI_SERVER_FQDN/ai/ai-agent-for-gitlab/agent-runner@develop\n    inputs: {\"tags\":[\"ai-agent\"]}'
  assert_output_contains '"action":"create","file_path":"README.md"'
}

@test "central pipeline: component ref overrides the default branch" {
  run central_run -e COMPONENT_REF=v0.5.0
  [ "$status" -eq 0 ]
  assert_output_contains 'agent-runner@v0.5.0'
}

@test "central pipeline: new component project is imported, runner waits for the import" {
  run central_run -e MOCK_NO_COMPONENT=1
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_contains '"import_url":"https://user:secret@github.com/m13tLabs/ai-agent-for-gitlab.git"'
  assert_output_contains '"visibility":"private"'
  assert_output_contains 'POST /api/v4/projects/31/members {"user_id":7,"access_level":50}'
  # Import still running: no catalog, no runner project yet (next CronJob run).
  assert_output_lacks "graphql"
  assert_output_lacks "agent-runner\",\"path\""
}

@test "central pipeline: missing settings fail the setup" {
  run setup_run -e CENTRAL_PIPELINE_ENABLED=true -e COMPONENT_PROJECT=ai/x
  assert_output_contains "FAILED: Missing COMPONENT_CLONE_URL"
}

@test "central pipeline on Premium: existing component project becomes a pull mirror, synced every run" {
  run central_run -e MOCK_EDITION=premium
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_contains 'PUT /api/v4/projects/30 {"description":"CI/CD component \"agent-runner\" of the AI agent for GitLab, mirrored from https://github.com/m13tLabs/ai-agent-for-gitlab.'
  assert_output_contains '"mirror":true,"import_url":"https://user:secret@github.com/m13tLabs/ai-agent-for-gitlab.git","mirror_trigger_builds":false,"mirror_overwrites_diverged_branches":true'
  assert_output_contains "POST /api/v4/projects/30/mirror/pull"
  # Runner project setup continues although the triggered update now runs.
  assert_output_contains "POST /api/v4/projects/32/repository/commits"
}

@test "central pipeline on Premium: new component project is created as a pull mirror" {
  run central_run -e MOCK_EDITION=premium -e MOCK_NO_COMPONENT=1
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_contains 'POST /api/v4/projects {"name":"ai-agent-for-gitlab"'
  assert_output_contains '"mirror":true,"mirror_trigger_builds":false'
  # First import still running: no sync trigger, no runner project yet.
  assert_output_lacks "mirror/pull"
  assert_output_lacks "agent-runner\",\"path\""
}

@test "central pipeline without Premium (EE unlicensed, CE) or with mirror off: import only" {
  for args in "-e MOCK_EDITION=ee" "-e MOCK_EDITION=ce" "-e MOCK_EDITION=premium -e COMPONENT_MIRROR=false"; do
    # shellcheck disable=SC2086
    run central_run $args
    [ "$status" -eq 0 ]
    assert_output_contains "OK"
    assert_output_contains "imported from https://github.com/m13tLabs/ai-agent-for-gitlab."
    assert_output_lacks '"mirror":true'
    assert_output_lacks "mirror/pull"
  done
}
