#!/usr/bin/env bats
#
# Tests for the gitlabSetup entrypoint (src/setup.ts) in the gitlab-app image:
# fixtures/setup-mock.mjs runs it inside the image against an in-process
# GitLab + Kubernetes API mock and prints the writes it received. See the
# mock for the instance layout (groups, projects, the bot).

load test_helper

setup_file() {
  require_image
}

# setup_run [-e VAR=value ...] -> mock output (writes + OK/FAILED)
setup_run() {
  docker run --rm -v "$BATS_TEST_DIRNAME/fixtures:/test:ro" "$@" "$IMAGE" node /test/setup-mock.mjs
}

assert_output_lacks() {
  if [[ "$output" == *"$1"* ]]; then
    printf 'expected output not to contain: %s\nactual: %s\n' "$1" "$output" >&2
    return 1
  fi
}

@test "default ['*']: only top-level groups get a membership" {
  run setup_run
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_contains "POST /api/v4/groups/1/members"
  assert_output_contains "POST /api/v4/groups/3/members"
  # team-a/sub inherits from team-a; gone is marked for deletion.
  assert_output_lacks "/api/v4/groups/2/"
  assert_output_lacks "/api/v4/groups/4/"
}

@test "default ['*']: every active project gets the comment webhook" {
  run setup_run
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  # Existing hook (found by name) is updated, the others are created.
  assert_output_contains 'PUT /api/v4/projects/10/hooks/99 {"name":"ai-agent-for-gitlab"'
  assert_output_contains "POST /api/v4/projects/11/hooks"
  assert_output_contains "POST /api/v4/projects/12/hooks"
  assert_output_contains '"note_events":true,"merge_requests_events":false,"push_events":false'
  assert_output_contains '"token":"hook-secret"'
  # Archived project is skipped.
  assert_output_lacks "/api/v4/projects/13/"
}

@test "project membership is skipped when inherited, added otherwise" {
  run setup_run
  [ "$status" -eq 0 ]
  assert_output_lacks "POST /api/v4/projects/10/members"
  assert_output_contains 'POST /api/v4/projects/11/members {"user_id":7,"access_level":30}'
}

@test "system hook is still registered for merge request events" {
  run setup_run
  [ "$status" -eq 0 ]
  assert_output_contains 'POST /api/v4/hooks {"name":"ai-agent-for-gitlab"'
}

@test "globs select matching projects, first entry's settings win" {
  run setup_run -e SETUP_GROUPS='[]' \
    -e SETUP_PROJECTS='[{"path":"TEAM-A/SUB/*","accessLevel":40},"team-a/*"]'
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_lacks "/api/v4/groups/"
  assert_output_contains 'POST /api/v4/projects/11/members {"user_id":7,"access_level":40}'
  assert_output_contains "PUT /api/v4/projects/10/hooks/99"
  assert_output_lacks "/api/v4/projects/12/"
}

@test "merge request events on project hooks only without the system hook" {
  run setup_run -e SYSTEM_HOOK_ENABLED=false -e SETUP_GROUPS='[]' -e SETUP_PROJECTS='["team-b/tool"]'
  [ "$status" -eq 0 ]
  assert_output_contains '"merge_requests_events":true'
  assert_output_lacks "/api/v4/hooks "

  run setup_run -e SETUP_GROUPS='[]' \
    -e SETUP_PROJECTS='[{"path":"team-b/tool","mergeRequestsEvents":true}]'
  [ "$status" -eq 0 ]
  assert_output_contains 'POST /api/v4/projects/12/hooks'
  assert_output_contains '"merge_requests_events":true'
}

@test "plain paths are looked up directly, unknown ones are skipped" {
  run setup_run -e SETUP_GROUPS='team-b,missing' -e SETUP_PROJECTS='["team-b/tool","nope/nope"]'
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_contains "POST /api/v4/groups/3/members"
  assert_output_lacks "/api/v4/groups/1/"
  assert_output_contains "POST /api/v4/projects/12/hooks"
  assert_output_lacks "/api/v4/projects/11/"
}

@test "empty lists turn the group and project steps off" {
  run setup_run -e SETUP_GROUPS='[]' -e SETUP_PROJECTS='[]'
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_lacks "/members"
  assert_output_lacks "/api/v4/projects/"
}

@test "invalid SETUP_PROJECTS fails the setup" {
  run setup_run -e SETUP_PROJECTS='[{"accessLevel":40}]'
  assert_output_contains "FAILED: SETUP_PROJECTS[0] needs a path"
}

@test "deployment is left alone while values and webhook secret are unchanged" {
  run setup_run -e RESTART_DEPLOYMENT=web -e CONFIG_CHECKSUM=chart-sum
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_lacks "/deployments/web"
}

@test "deployment restarts when the webhook secret changed (e.g. regenerated by Argo CD)" {
  run setup_run -e RESTART_DEPLOYMENT=web -e CONFIG_CHECKSUM=chart-sum -e WEBHOOK_SECRET=regenerated
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_contains '"token":"regenerated"'
  assert_output_contains "PATCH /apis/apps/v1/namespaces/test/deployments/web"
}

# setup_run with the central pipeline on (see the mock for its projects and repos)
central_run() {
  setup_run -e CENTRAL_PIPELINE_ENABLED=true \
    -e COMPONENT_PROJECT=ai/ai-agent-for-gitlab \
    -e COMPONENT_CLONE_URL=file:///tmp/source.git \
    -e RUNNER_PROJECT=ai/agent-runner \
    -e SETUP_GROUPS='[]' -e SETUP_PROJECTS='[]' "$@"
}

@test "central pipeline: Job pushes the source into the component project, runner project set up with the bot as Owner" {
  run central_run -e RUNNER_COMPONENT_INPUTS='{"tags":["ai-agent"]}'
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  # Component project: description, bot Owner, all branches and tags pushed,
  # default branch follows the source's HEAD, catalog on.
  assert_output_contains 'PUT /api/v4/projects/30 {"description":"CI/CD component \"agent-runner\" of the AI agent for GitLab, synced from file:///tmp/source.'
  assert_output_contains 'POST /api/v4/projects/30/members {"user_id":7,"access_level":50}'
  assert_output_contains "REFS refs/heads/develop"
  assert_output_contains "REFS refs/heads/feature"
  assert_output_contains "REFS refs/tags/v0.5.0"
  assert_output_contains 'PUT /api/v4/projects/30 {"default_branch":"develop"}'
  assert_output_contains 'catalogResourcesCreate(input: { projectPath: $p })'
  # CE: no pull mirror.
  assert_output_lacks '"mirror":true'
  # Runner project created in group ai (20), bot Owner, files on a new main branch.
  assert_output_contains 'POST /api/v4/projects {"name":"agent-runner","path":"agent-runner","namespace_id":20'
  assert_output_contains 'POST /api/v4/projects/32/members {"user_id":7,"access_level":50}'
  assert_output_contains 'POST /api/v4/projects/32/repository/commits {"branch":"main"'
  assert_output_contains 'component: $CI_SERVER_FQDN/ai/ai-agent-for-gitlab/agent-runner@develop\n    inputs:\n      tags:\n        - \"ai-agent\"\n'
  assert_output_contains '"action":"create","file_path":"README.md"'
}

@test "central pipeline: new component project is created empty and filled by the push in the same run" {
  run central_run -e MOCK_NO_COMPONENT=1
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_contains 'POST /api/v4/projects {"name":"ai-agent-for-gitlab","path":"ai-agent-for-gitlab","namespace_id":20'
  assert_output_lacks "import_url"
  assert_output_contains "REFS refs/heads/develop"
  assert_output_contains 'PUT /api/v4/projects/31 {"default_branch":"develop"}'
  # No waiting for an import: the runner project follows right away.
  assert_output_contains "POST /api/v4/projects/32/repository/commits"
}

@test "central pipeline: component ref (the chart's release tag) overrides the default branch" {
  run central_run -e COMPONENT_REF=v0.5.0 \
    -e RUNNER_COMPONENT_INPUTS='{"image":"m13t/ai-agent-for-gitlab-agent","job-name":"ai-review","version":"0.7.1"}'
  [ "$status" -eq 0 ]
  assert_output_contains 'agent-runner@v0.5.0\n    inputs:\n      image: \"m13t/ai-agent-for-gitlab-agent\"\n      job-name: \"ai-review\"\n      version: \"0.7.1\"\n'
}

@test "central pipeline: a ref missing from the component project fails with an explanation" {
  run central_run -e COMPONENT_REF=v9.9.9
  assert_output_contains 'FAILED: Ref "v9.9.9" not found in ai/ai-agent-for-gitlab (synced from file:///tmp/source)'
  assert_output_lacks "repository/commits {"
}

@test "central pipeline on Premium: pull mirror enabled on top of the Job's sync" {
  run central_run -e MOCK_EDITION=premium
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_contains "REFS refs/heads/develop"
  assert_output_contains '"mirror":true,"import_url":"file:///tmp/source.git","mirror_trigger_builds":false,"mirror_overwrites_diverged_branches":true'
  assert_output_contains "POST /api/v4/projects/30/mirror/pull"
}

@test "central pipeline on Premium: a mirror GitLab can't reach only warns, the Job's sync carries on" {
  run central_run -e MOCK_EDITION=premium -e MOCK_MIRROR_FAILS=1
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_contains "REFS refs/heads/develop"
  assert_output_lacks "mirror/pull"
  assert_output_contains "POST /api/v4/projects/32/repository/commits"
}

@test "central pipeline without Premium (EE unlicensed, CE) or with mirror off: no pull mirror" {
  for args in "-e MOCK_EDITION=ee" "-e MOCK_EDITION=ce" "-e MOCK_EDITION=premium -e COMPONENT_MIRROR=false"; do
    # shellcheck disable=SC2086
    run central_run $args
    [ "$status" -eq 0 ]
    assert_output_contains "OK"
    assert_output_contains "REFS refs/heads/develop"
    assert_output_lacks '"mirror":true'
    assert_output_lacks "mirror/pull"
  done
}

@test "central pipeline: an unreachable source fails with an explanation and without its credentials" {
  run central_run -e COMPONENT_CLONE_URL=https://user:s3cr3t-pw@unreachable.invalid/ai-agent-for-gitlab.git
  assert_output_contains "FAILED: Could not clone https://unreachable.invalid/ai-agent-for-gitlab"
  assert_output_contains "a proxy through additionalEnvs (HTTPS_PROXY)"
  assert_output_lacks "s3cr3t-pw"
}

@test "central pipeline: missing settings fail the setup" {
  run setup_run -e CENTRAL_PIPELINE_ENABLED=true -e COMPONENT_PROJECT=ai/x
  assert_output_contains "FAILED: Missing COMPONENT_CLONE_URL"
}

@test "central pipeline: extra includes and extra config are appended to the runner's .gitlab-ci.yml" {
  run central_run -e COMPONENT_REF=v0.5.0 \
    -e RUNNER_COMPONENT_INPUTS='{"job-name":"ai-review"}' \
    -e RUNNER_EXTRA_INCLUDES='[{"project":"infra/jobs/gitlab-components/helpers","ref":"v1.0.0","file":".gitlab-ci/include.yml"}]' \
    -e RUNNER_EXTRA_CONFIG=$'ai-review:\n  extends:\n    - .proxy_setup\n'
  [ "$status" -eq 0 ]
  assert_output_contains 'agent-runner@v0.5.0\n    inputs:\n      job-name: \"ai-review\"\n  - project: \"infra/jobs/gitlab-components/helpers\"\n    ref: \"v1.0.0\"\n    file: \".gitlab-ci/include.yml\"\n\nai-review:\n  extends:\n    - .proxy_setup\n'
}

@test "central pipeline: extra includes must be a list of maps" {
  run central_run -e RUNNER_EXTRA_INCLUDES='{"project":"x"}'
  assert_output_contains "FAILED: RUNNER_EXTRA_INCLUDES must be a JSON array of objects"
}

@test "central pipeline: an existing runner .gitlab-ci.yml is updated by default" {
  run central_run -e MOCK_RUNNER_EXISTS=1
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_contains '"actions":[{"action":"update","file_path":".gitlab-ci.yml"'
  # README exists: created once, never updated.
  assert_output_lacks '"file_path":"README.md"'
  assert_output_lacks 'POST /api/v4/projects {"name":"agent-runner"'
}

@test "central pipeline with initialSetupOnly: an existing runner project's files are left alone" {
  # The ref isn't even checked when nothing is written.
  run central_run -e MOCK_RUNNER_EXISTS=1 -e RUNNER_INITIAL_SETUP_ONLY=true -e COMPONENT_REF=v9.9.9
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_lacks "repository/commits {"
  # Membership is still ensured.
  assert_output_contains 'POST /api/v4/projects/32/members {"user_id":7,"access_level":50}'
}

@test "central pipeline with initialSetupOnly: a new runner project still gets its files" {
  run central_run -e RUNNER_INITIAL_SETUP_ONLY=true
  [ "$status" -eq 0 ]
  assert_output_contains "OK"
  assert_output_contains 'POST /api/v4/projects {"name":"agent-runner"'
  assert_output_contains '"action":"create","file_path":".gitlab-ci.yml"'
  assert_output_contains '"action":"create","file_path":"README.md"'
}
